### ISSUE TITLE
Problems installing and running the game

### ISSUE THREAD

**Issue by freefri** [mmtrt/leagueoflegends#1]
Hello.
Since League of Legends 8.12 (summer 2018) Riot release an anti-cheat update which was causing the game to crash on launch (see League of Legends boards: Game client anti-cheat known issues and fixes) As some users [are reporting](https://www.youtube.com/watch?v=gM-gyxElQ_s) the game should be working again, but I'm still facing some problems:

1. In any case, I've managed to install the game properly, but the game **crashes** before the login screen (when you wait with the splash image of the 10 champions), right after champion select (the same that was happening right after Riot released the anti-cheat update).  No clue what was happening, but the bug report window was coming once and again.

2. I've tried then to uninstall the snap and install a new snap from scratch (with the latest update https://github.com/mmtrt/leagueoflegends/commit/3940f91be377a5be0876a81862fdf08a6ab47bbe). But now I'm facing another issue while installing the client. I'm getting the following message (and the updater stays in 0% for hours):

> LeagueClient.exe(0000015E): ALWAYS|           <unknown-plugin>| Riot::RADS::Patching::RemoteFileServerHTTP::EnumerateAvailableReleases: Using cached releaselisting as downloaded releaselisting was not modified.

![screenshot from 2018-09-30 18-45-25](https://user-images.githubusercontent.com/2754631/46260008-1db6b900-c4e1-11e8-9894-da078f072bec.png)

I'm new to snap, but I'm experienced with Linux, if anyone could give me a hint I could investigate more.

**Comment by mmtrt** [comment]
* on champ select launcher do crash sometimes but it recovers and relaunches or it loads up game to loading screen so theses issues are known though next wine version has some changes related to this game not sure that will fix theses issues.

* as for updating and installing the game there seems to be issues in the game launcher though some new deps are needed for this game found on reddit about it so I'll add them after some testing tomorrow then update the snap with new changes.

**Comment by mmtrt** [comment]
can you post output of these 

`snap version`
`snap info core`

**Comment by freefri** [comment]
Thank you for the reply.

About champ select issue, I've tried to reconnect to a customized game, at least 4 times without success, I could give more details (like logs), when I manage to install the game again.

I'm posting my system details:

`snap version`
snap    2.35
snapd   2.35
series  16
debian  9
kernel  4.9.0-3-amd64

` snap info core`
name:      core
summary:   snapd runtime environment
publisher: Canonical✓
license:   unset
description: |
  The core runtime environment for snapd
type:         core
snap-id:      99T7MUlRhtI3U0QFgl5mXXESAiSwt776
tracking:     stable
refresh-date: 5 days ago, at 11:45 CEST
channels:                                         
  stable:    16-2.35                  (5328) 92MB -
  candidate: 16-2.35.2                (5548) 92MB -
  beta:      16-2.35.2                (5548) 92MB -
  edge:      16-2.35.2+git954.b1b6b89 (5603) 92MB -
installed:   16-2.35                  (5328) 92MB core

**Comment by mmtrt** [comment]
Did you tried the snap with latest changes posted.

Update it

`snap refresh leagueoflegends --edge --devmode`

**Comment by freefri** [comment]
I'm currently using the latest snap Version 1.0 Revision 10 with the same problem when patching (see screenshot on top) 

> LeagueClient.exe(00000123): ALWAYS|           <unknown-plugin>| Riot::RADS::Patching::RemoteFileServerHTTP::EnumerateAvailableReleases: Using cached releaselisting as downloaded releaselisting was not modified.

**Comment by mmtrt** [comment]
just pushed wine update to `wine-platform` snap update that and try again with clean `~/snap/leagueoflegends`

**Comment by apolitech** [comment]
> just pushed wine update to `wine-platform` snap update that and try again with clean `~/snap/leagueoflegends`

Hey , I've got the same problem. I've remove and install again the snap like 10 min ago but the updater is stuck at 0%.
Here is a part of the log file
[file.txt](https://github.com/mmtrt/leagueoflegends/files/2434014/file.txt)

"LeagueClient.exe(00000009): ALWAYS| Queued Dradis event to be sent.
LeagueClient.exe(00000009): ALWAYS| Ux state set to ShowMain.
LeagueClient.exe(00000090): ALWAYS|           <unknown-plugin>| Riot::RADS::Patching::RemoteFileServerHTTP::EnumerateAvailableReleases: Using cached releaselisting as downloaded releaselisting was not modified.
LeagueClient.exe(00000092): ALWAYS|           <unknown-plugin>| Riot::RADS::Patching::RemoteFileServerHTTP::EnumerateAvailableReleases: Using cached releaselisting as downloaded releaselisting was not modified.
LeagueClient.exe(00000095): ALWAYS|           <unknown-plugin>| Riot::RADS::Patching::RemoteFileServerHTTP::EnumerateAvailableReleases: Using cached releaselisting as downloaded releaselisting was not modified.
LeagueClient.exe(00000097): ALWAYS|           <unknown-plugin>| Riot::RADS::Patching::RemoteFileServerHTTP::EnumerateAvailableReleases: Using cached releaselisting as downloaded releaselisting was not modified.
"

**Comment by freefri** [comment]
After updating and removing league files (`rm -R ~/snap/leagueoflegends`) I've got the client running, but my first problem is still there:

> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast

![screenshot from 2018-10-01 17-37-21](https://user-images.githubusercontent.com/2754631/46299055-d3950c80-c5a0-11e8-98da-7bea3460733a.png)

This is coming right after champion select. I've tried to reconnect many times without success.

**Comment by mmtrt** [comment]
gpu vendor and drivers running in your system.

**Comment by freefri** [comment]
Nvidia GTX 560 Ti

I was using the driver Nvidia Driver version 375.66
![screenshot from 2018-10-01 17-52-02](https://user-images.githubusercontent.com/2754631/46300531-418f0300-c5a4-11e8-8eed-7a72c7871184.png)

I've decided to upgrade to the latest drive in the repos, version 384.130
After finishing installing the update, I've reboot the system and now I'm getting again the error:

> LeagueClient.exe(000000BD): ALWAYS|           <unknown-plugin>| Riot::RADS::Patching::RemoteFileServerHTTP::EnumerateAvailableReleases: Using cached releaselisting as downloaded releaselisting was not modified.

![screenshot from 2018-10-01 18-05-19](https://user-images.githubusercontent.com/2754631/46300665-96cb1480-c5a4-11e8-8acf-5138dc49c19d.png)

**Comment by mmtrt** [comment]
weird I'm also having same bugsplat error on fresh game install but its not launching at all on my laptop but already updated game copied from lutris install to 

`~/snap/leagueoflegends/common/.wine/drive_c/` works fine on same machine.

can you test this league snap created by other dev see if that works for you

`snap install leagueoflinux --edge -devmode`

**Comment by apolitech** [comment]
> snap install leagueoflinux --edge
 Yea this will not start Fontconfig error: Cannot load default config file =)))

**Comment by mmtrt** [comment]
ah ok, game download issue seems likely fixed itself though I removed fresh installed riotgames folder inside wineprefix then relaunched game to download the setup again though game seems to break too often when new updates install surely backup riotgames folder timely then restore it when game breaks <-- That still create also create minor issue though game data currupt still get fixed by small game update after the repair.

**Comment by freefri** [comment]
I'm getting a similar issue with different error in leagueoflinux snap (https://github.com/Coffeeinator/leagueoflinux/issues/2)

I've tested again to run leagueoflegends snap and the updater worked, so do you think the update issue is related with Riot changes and updates? Or maybe I've installed something important after intalling the new leagueoflinux snap?

The game is still crashing before champion select with the following errors:

> libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

**Comment by mmtrt** [comment]
gamg is quite buggy in wine with breaking on each updates though snaps different work space and can you try this Paste `X3d_Platform=1` under `[General]` in `game.cfg` (~/snap/leagueoflegends/common/drive_c/RiotGames/LeagueofLegends/Config) folder

**Comment by apolitech** [comment]
don't know what you did but after a fresh install everything works as intended .

**Comment by Nikola135** [comment]
Hi.

I have same problem. After first run after install, everything works fine. Next run, after system restart, game hangs on that „League of Legends ETA 0 MINS 0.0MB / 0.0MB“ forever.

Solved only by snap remove, snap install. Is there faster way to fix this then having to reinstall all game every time? 

Also, my friend that have Windows said to me that's been happening on Windows also, but it hangs only about 10 minutes, and then loads client.

My system:
Zorin OS 12 Lite (Based on Ubuntu 16.04 with Xfce + Compiz)
CPU: AMD Ryzen 7 2700x
GPU: Nvida GeForce GTX 1060 6gb
RAM: 32gb
![screenshot31](https://user-images.githubusercontent.com/16721247/46407025-c9445100-c70d-11e8-9816-2d4ef4a24df4.png)

**Comment by Synaxis** [comment]
I suggest testing it in Ubuntu 18.04 or openSuse. I always have issues with wine/snap in other distros. i mean this is too new.
It works fine here in Ubuntu 18.04 MATE

**Comment by sbiliaiev** [comment]
I have the same issue

@fportillo92 method with using
> sudo leagueoflegends
doesn't work
here is the output: https://pastebin.com/iRDtYMPe

**Comment by sbiliaiev** [comment]
> game is quite buggy in wine with breaking on each updates though snaps have different work space which would work fine and can you try this Paste `X3d_Platform=1` under `[General]` in `game.cfg` (~/snap/leagueoflegends/common/drive_c/RiotGames/LeagueofLegends/Config) folder to run game in OpenGL mode.
> 
> EDIT: maybe try updating your drivers to current stable version which is `390.87`

@mmtrt I've tried your solution but I do not have _drive_c_ in _common_ directory:
![image](https://user-images.githubusercontent.com/6455835/46504700-5f27cb00-c837-11e8-8b7e-93f1ac043064.png)
The Only thing that I ahve inside _League of Legends_ directory is empty directory named _Replays_ so I guess that the game hasn't installed correctly

I'll add some more information tomorrow

**Comment by mmtrt** [comment]
folders are hidden there that's why you can not see them so show hidden files then inside of .wine folder there will be drive_c.

I missed the .wine in full path.

**Comment by freefri** [comment]
I've made a clean install of Ubuntu 18.04 with the latest Nvidia Driver 390.48 for my GTX 560 Ti. And with the old install of the snap (I've kept my old /home directory and the /home/user/snap directory too) it worked without any problems.

I think the problem was related with the Nvidia drivers in Debian 9, not with this project (league snap).

**Comment by freefri** [comment]
I think we should close this issue. For anyone having problems installing/runing the game, please open new issues with new descriptions.
