### ISSUE TITLE
Client doesnt start (riot bugsplat)

### ISSUE THREAD

**Issue by Lavande-aspic** [mmtrt/leagueoflegends#95]
Hello again, I have encountered a new issue ! When launching the game with snap run leagueoflegends I get riot's bugsplat. And it opens many times if I just wait. 
Here are the system specs. 

System:    Kernel: 4.15.0-66-generic x86_64 bits: 64 Desktop: Gnome 3.28.4
Distro:       Ubuntu 18.04.3 LTS
Machine:   Device: laptop System: LENOVO product: 2349U4B v: ThinkPad T430
CPU:         Dual core Intel Core i5-3320M (-MT-MCP-) cache: 3072 KB
                 clock speeds: max: 3300 MHz 1: 1206 MHz 2: 1219 MHz 3: 1205 MHz 4: 1201 MHz
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller
           Display Server: x11 (X.Org 1.19.6 ) driver: i915 Resolution: 1600x900@60.01hz
           OpenGL: renderer: Mesa DRI Intel Ivybridge Mobile version: 4.2 Mesa 19.0.8

I think these lines are linked with the bugsplat.

```
LeagueClient.exe(000001B5): ALWAYS| Queued Dradis event to be sent.
LeagueClient.exe(000001B5): ALWAYS| Ux state set to HideAll.
LeagueClient.exe(000001B5): ALWAYS| Ux state set to Quit.
LeagueClient.exe(000001B5): ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__js_memory_stats_summary
```

You can look at the full log [here](https://github.com/mmtrt/leagueoflegends/files/3809319/launchLogLoL.txt), and see a screenshot of the bugsplat.

Additional info: I got it to run on a T420 which has an Intel Core i5-2520M running a Intel 2nd Generation Core Processor Family Integrated Graphics. The same driver (i915) is used, the only difference is the openGl renderer (works on an sandybridge (v3.3 with MESA 18.3), problem is on the ivybrige (v4.2 with Mesa 19.0.8).

![Capture_decran_de_2019-11-05_14-29-11](https://user-images.githubusercontent.com/32075914/68214184-43b06600-ffdd-11e9-82a1-432c5e16c279.png)

**Comment by mmtrt** [comment]
Try changing wineprefix os to `winxp` via this command. 

`leagueoflegends.winecfg`

**Comment by stuartfoxcroft** [comment]
Also having this issue, wineprefix OS is still set to winxp but bugsplats still occurring.

**Comment by stuartfoxcroft** [comment]
Only occurs infrequently however and was resolved upon killing all running wine processes and running the snap again.

**Comment by Lavande-aspic** [comment]
Tried to set it to winxp, the problem persists.

**Comment by mmtrt** [comment]
Try clean wineprefix check pinned issue for howto

**Comment by TheoOliveira** [comment]
Idid a fresh install in a Kde Neon and this issue show up. I've try to reinstall but it continued. After a while, I tried to change to xp and run through terminal and worked. Not sure if it was the desktop entry or both things. I gonna try to test it out

**Comment by TheoOliveira** [comment]
Still not running. It doesnt show the bugsplat but runs the new small riot game loading and then nothing. I will try to post the log

**Comment by Ignacy-s** [comment]
Depending on your system it might take a while tu run. 4core 3.2ghz intel from 2014 here and nvme ssd, it took over a minute to update last time. After that the game launched by itself again.
It's normal if the game doesn't run sometimes, giving errors. It takes up to a few times of starting, waiting for an error and killing all game processes, before the game will run.
@TheoOliveira have you used the workaround that disables the new launcher by setting it's ownership to root?

**Comment by TheoOliveira** [comment]
Well, My notebook is Samsung 8gb ram and video card 2gb. core i7 so that's not the problem. but I haven't check this workaround. is it here, somewhere?

**Comment by Ignacy-s** [comment]
> 8gb ram and video card 2gb. core i7
Looks like more than enough.

[Workaround for lol ver 9.21](https://github.com/mmtrt/leagueoflegends#game-not-starting-unhandled-exception-and-midimap_drvopen-in-lol-ver-921)
When I see (and have :D) issues that get a solution posted, I try to post them to the readme.md of this snap package. Please comment (and fix if you can) if there are some errors or it's difficult to read/understand. My plan was to make it easier for everyone to enjoy league, and to be able to find all fixes without even looking at "Issues".
